
import sys
import getopt
import os
import shutil
import logging
import json
sys.path.append(os.path.join(os.path.dirname(
    os.path.realpath(__file__)), os.pardir+'/modules/models'))
import transaction
import fpsFile


class XMLConverter:
    
    def convert(self, file_id, processing_date_short, submission_id, amount, fpid, processing_time, receiver_branch_code, receiver_account_number, reference_information, orig_customer_account_name):
        xmlTemplate = """<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Generated by Vocalink FPS Report Server -->
<FPSDocument xmlns="http://www.jvcoURL.com/schemas/fps" xmlns:cmn="http://www.jvcoURL.com/schemas/fps/common" xmlns:env="http://www.jvcoURL.com/schemas/fps/common/envelope" xmlns:iso="http://www.jvcoURL.com/schemas/fps/common/iso" xmlns:rptcmn="http://www.jvcoURL.com/schemas/fps/report/common"  xmlns:di="http://www.jvcoURL.com/schemas/fps/report/dcaInput" xmlns:sd="http://www.jvcoURL.com/schemas/fps/signableDocument"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  Title="DCAInputReport" created="2018-09-20T10:01:09" schemaVersion="2.8">
  <Data>
    <sd:DCAInputReport>
      <di:Header><di:ReportTitle>DCA Input Report</di:ReportTitle><di:CorporateID>06440380</di:CorporateID><di:Currency>826</di:Currency><di:SubmissionID>%(submission_id)s</di:SubmissionID><di:SubmissionStatus>0</di:SubmissionStatus></di:Header>
      <di:OriginatorIteration>
        <di:FileID>%(file_id)s</di:FileID>
        <di:FileStatus>0</di:FileStatus>
        <di:Date>%(processing_date_short)s</di:Date>
        <di:OutwardAcceptedValue Ccy="826">%(amount)s</di:OutwardAcceptedValue>
        <di:OutwardAcceptedVolume>1</di:OutwardAcceptedVolume>
        <di:OutwardRejectedValue Ccy="826">0.00</di:OutwardRejectedValue>
        <di:OutwardRejectedVolume>0</di:OutwardRejectedVolume>
        <di:PaymentIteration>
          <di:FPID>%(fpid)s</di:FPID>
          <di:Time>%(processing_time)s</di:Time>
          <di:OrigCustomerSortCode>200000</di:OrigCustomerSortCode>
          <di:OrigCustomerAccountNumber>23622398</di:OrigCustomerAccountNumber>
          <di:BeneficiaryCreditInstitution>%(receiver_branch_code)s</di:BeneficiaryCreditInstitution>
          <di:BeneficiaryCustomerAccountNumber>%(receiver_account_number)s</di:BeneficiaryCustomerAccountNumber>
          <di:Amount Ccy="826">%(amount)s</di:Amount>
          <di:Accepted>true</di:Accepted>
          <di:QualifierCode>0000</di:QualifierCode>
          <di:ProcessedAsynchronously>TRUE</di:ProcessedAsynchronously>
          <di:ReferenceInformation>%(reference_information)s</di:ReferenceInformation>
          <di:OrigCustomerAccountName>%(orig_customer_account_name)s</di:OrigCustomerAccountName>
        </di:PaymentIteration>
      </di:OriginatorIteration>
      <di:OutwardAcceptedValue Ccy="826">%(amount)s</di:OutwardAcceptedValue>
      <di:OutwardAcceptedVolume>1</di:OutwardAcceptedVolume>
      <di:OutwardRejectedValue Ccy="826">0.00</di:OutwardRejectedValue>
      <di:OutwardRejectedVolume>0</di:OutwardRejectedVolume>
    </sd:DCAInputReport>
  </Data><SignatureMethod>Vanilla</SignatureMethod><Signature>MIIRngYJKoZIhvcNAQcCoIIRjzCCEYsCAQExCzAJBgUrDgMCGgUAMAsGCSqGSIb3DQEHAaCCDzkw
ggTSMIIDuqADAgECAhBMl3hNpS4bS+TswCWYpqiXMA0GCSqGSIb3DQEBCwUAMIGRMQswCQYDVQQG
EwJHQjERMA8GA1UEChMIVm9jYUxpbmsxHzAdBgNVBAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsx
NTAzBgNVBAsTLENsYXNzIDIgTWFuYWdlZCBQS0kgSW5kaXZpZHVhbCBTdWJzY3JpYmVyIENBMRcw
FQYDVQQDEw5JVCBTZWN1cml0eSBHMzAeFw0xODA1MjEwMDAwMDBaFw0xOTA1MjEyMzU5NTlaMIG2
MREwDwYDVQQKFAhWb2NhTGluazEXMBUGA1UECxQOSVQgU2VjdXJpdHkgRzMxRjBEBgNVBAsTPXd3
dy52ZXJpc2lnbi5jb20vcmVwb3NpdG9yeS9DUFMgSW5jb3JwLiBieSBSZWYuLExJQUIuTFREKGMp
OTYxIDAeBgNVBAMTF1V0aWxpdHkgUHJvZCBBUDIwMSAyMDE4MR4wHAYJKoZIhvcNAQkBFg9jYUB2
b2NhbGluay5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDq213YgH+UQBG1JO71
UZZimbaSi+ly2GlMiZCVqfnmyghnBFHG+U+FjSrqupd7e6//jdsYPtlDi/LvXLvI5iW4IuDifVyt
AERjLHl1m3Z2bf9I6cBTHPC909FzAXoOLgqETFWROusVx3/pvDLffsTRWLs8SFzN1cEeEVDk2sMB
dghthcVe0Qhy+PafEN6prvz8pNjmh/t0q9UaDEprHU9+oNf1XfMLz1zgnmLW9NPG4k8OdG9hzEsG
/30xXMbZLoj28lD8gwEPu/4IVJfvHk9khpHJHJIO+MnR2gR1ynjs/qt/nCBgQeWZnFLA6LsBZNYt
oJ3D/8BvfYtAAC+xh9KTAgMBAAGjgf4wgfswHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwME
MAkGA1UdEwQCMAAwUgYDVR0fBEswSTBHoEWgQ4ZBaHR0cDovL29uc2l0ZWNybC50cnVzdHdpc2Uu
Y29tL1ZvY2FMaW5rSVRTZWN1cml0eUczL0xhdGVzdENSTC5jcmwwDgYDVR0PAQH/BAQDAgbAMEUG
A1UdIAQ+MDwwOgYLYIZIAYb4RQEHFwIwKzApBggrBgEFBQcCARYdaHR0cHM6Ly93d3cudHJ1c3R3
aXNlLmNvbS9ycGEwEQYJYIZIAYb4QgEBBAQDAgeAMBEGCmCGSAGG+EUBBgkEAwEB/zANBgkqhkiG
9w0BAQsFAAOCAQEABDA81z1cMgg2QpqISD1uG8BnHvG5O5sa0kZVCrbtdF1R+y7/mnKDGFVvEaNM
0Eeab91NlWbsi7dzPax+GXSfCk6cBBN8cK8zuPpr2AjZjhGcdPrNtXDKkUoAifzXBFIaPNvgEg4w
eD2GNrCTRTuttLcM8iu5+qfX2/LyKfehW1+vTRWcAXf8Uv30YQzbWCzC61QykBK2R2PQklXUDIg6
qswL3M/1DRinojQICbf9+Agy5iBMzR8mIup2wcokIqb7n07Z1coTBtpBA8aMiTTXL1/6WMfQESR0
zSCCNWiMiw1kNHKsTFafdRZ6j7T+trOhKtkjLQZu/07XBv9wbCjVijCCBNswggPDoAMCAQICEEgD
qTHaSTzZgqH1+bMGeaEwDQYJKoZIhvcNAQELBQAwdDELMAkGA1UEBhMCR0IxJzAlBgNVBAoTHkJy
aXRpc2ggVGVsZWNvbW11bmljYXRpb25zIHBsYzEfMB0GA1UECxMWU3ltYW50ZWMgVHJ1c3QgTmV0
d29yazEbMBkGA1UEAxMSQlQgQ2xhc3MgMiBDQSAtIEczMB4XDTE1MDIxNzAwMDAwMFoXDTIwMDIx
NjIzNTk1OVowgZExCzAJBgNVBAYTAkdCMREwDwYDVQQKEwhWb2NhTGluazEfMB0GA1UECxMWU3lt
YW50ZWMgVHJ1c3QgTmV0d29yazE1MDMGA1UECxMsQ2xhc3MgMiBNYW5hZ2VkIFBLSSBJbmRpdmlk
dWFsIFN1YnNjcmliZXIgQ0ExFzAVBgNVBAMTDklUIFNlY3VyaXR5IEczMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEA5yCWeJCK4hXNN16gT0+8JpE9ZpwMgdpbZu7GIXa5yqqHkCrCAMfu
tGU4VcLD+gIE5AlfijCRMnX8QuoznzUQDribPSTTAjL6EBvSOIuwFMqhmuyS5H/381OvL4T4gFB1
xeHXfiJAb8gG9C4wlJ4gGplsntGOICuyn8j2ud7ImdpUdciwh0t/OGod2sLjB951vhnmLd0432dp
85+wbnGIjVqdLiSaJjymDV4UIO8EoCx6WUGOhI6emZlyuzSs6L8Hjbt35QTVtklmUCo37beETv80
UYz0m3zGKKqIoTu7xC5Ej6hh3S3//Jj9G2JyyKv2LCnW7HQn3Y0aVZtAcc2LfwIDAQABo4IBSTCC
AUUwEgYDVR0TAQH/BAgwBgEB/wIBADBBBgNVHR8EOjA4MDagNKAyhjBodHRwOi8vb25zaXRlY3Js
LnRydXN0d2lzZS5jb20vQlRDbGFzczJDQS1HMy5jcmwwDgYDVR0PAQH/BAQDAgEGMCgGA1UdEQQh
MB+kHTAbMRkwFwYDVQQDExBidDIwNDhjMlB1YjEtMjIzMB0GA1UdDgQWBBQ2ycGAaimLSVY1jiIE
zLLjp0GWvzByBgNVHSAEazBpMGcGC2CGSAGG+EUBBxcCMFgwKQYIKwYBBQUHAgEWHWh0dHBzOi8v
d3d3LnRydXN0d2lzZS5jb20vY3BzMCsGCCsGAQUFBwICMB8aHWh0dHBzOi8vd3d3LnRydXN0d2lz
ZS5jb20vcnBhMB8GA1UdIwQYMBaAFOh886x/6N1kBIe7W2W+j5D9ZBlbMA0GCSqGSIb3DQEBCwUA
A4IBAQBA9kkY+s9Da+/BewbAoMFgn3jJo6YO/Yx8yQconhiWkV4moeKKwa9iD2HkXWKD6EEw6zjk
5VwtNNXihDxsk2RG2QP2TEeae70dzeKEceaxTCna/RxuG/yhxRUzv9oebm9a73kKqeS1vYknAurW
PCy4Zqvg5oSi44zih+1GVkQ7A87OJuAfHYf+DhdI/VzBGs4XSTL6xUvanWMfE4Qu5Ckj7JNV51ol
x7H+ZRjzT1G7HPudQmo+uX2l8qbmwexAzNRs8bnUuo5DfONyV3uKGkIg15quGLVKuRdUBbUZ9gRG
N8/bgHC7Bkf/5IGz8/rOHkNhopw7pOGL43gd+uai9ptIMIIFgDCCBGigAwIBAgIQCOkLCTZINOv+
9+KMHHHUCzANBgkqhkiG9w0BAQsFADCByjELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWdu
LCBJbmMuMR8wHQYDVQQLExZWZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMTk5
OSBWZXJpU2lnbiwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MUUwQwYDVQQDEzxWZXJp
U2lnbiBDbGFzcyAyIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzMw
HhcNMTQxMjE2MDAwMDAwWhcNMjQxMjE1MjM1OTU5WjB0MQswCQYDVQQGEwJHQjEnMCUGA1UEChMe
QnJpdGlzaCBUZWxlY29tbXVuaWNhdGlvbnMgcGxjMR8wHQYDVQQLExZTeW1hbnRlYyBUcnVzdCBO
ZXR3b3JrMRswGQYDVQQDExJCVCBDbGFzcyAyIENBIC0gRzMwggEiMA0GCSqGSIb3DQEBAQUAA4IB
DwAwggEKAoIBAQCmJxT3dB2UrmECZU3Esy3/azb5RaSt0iw4b5+p4mYPbEzoltYe8xMQV7PwPzmT
EYnzzN0tEQiacLShBfASDmORSxUakC9ItUC+DbYFU9RRMTSFfUSWVQfGnv1VrKzm7U3dfd8DOowH
qpI/07UecGrh7aBE/Oo6auX0NCDzz/W6PLt8o7Ia26QZa+8La7DLXuFDZH4eNZMiK/Zc5PwOeQ5a
2QZRdWgoA9bVndKxAQMp04EdDeEWIGHpdYDYb90wF6sHWLK3lp01s9cAhgponOYYC6W1yz2kOjx5
M31/foZJDeTurVRaZgpV/qHXMVCaRO01iMXxvL0M9E5L7i8BcLTjAgMBAAGjggG1MIIBsTAPBgNV
HRMBAf8EBTADAQH/MBgGA1UdIAQRMA8wDQYLYIZIAYb4RQEHFwIwNwYDVR0fBDAwLjAsoCqgKIYm
aHR0cDovL2NybC53cy5zeW1hbnRlYy5jb20vcGNhMi1nMy5jcmwwDgYDVR0PAQH/BAQDAgEGMCkG
A1UdEQQiMCCkHjAcMRowGAYDVQQDExFBZmZTQ0MyLTIwNDgtMS02NzAdBgNVHQ4EFgQU6HzzrH/o
3WQEh7tbZb6PkP1kGVswgfAGA1UdIwSB6DCB5aGB0KSBzTCByjELMAkGA1UEBhMCVVMxFzAVBgNV
BAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQLExZWZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTowOAYD
VQQLEzEoYykgMTk5OSBWZXJpU2lnbiwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MUUw
QwYDVQQDEzxWZXJpU2lnbiBDbGFzcyAyIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0
aG9yaXR5IC0gRzOCEGFwy0mMX5hFKeewptlQW3owDQYJKoZIhvcNAQELBQADggEBAEXga33UsQhy
hYJvezZsOjN7kgEJdNW0qSxjiyrILMgJwWDjfa7PIFFlk2vWv5+rPwMiSkgWsGyAxu2n4pBnj7Ld
qiB1oEmcyBh035Dn1Cmyx+q/f2TaXwyHmUO9QDUKdmatk5+zIIz68cP0vxZpFmxDLt6sa8/bvdKT
zc+yiqOh6BORFgZOGqq+6wDg9GiL1f14jHadiYCmWx9trPJO3lDH3aSQQ/OegbWKgk9FgT0xTuF9
SkD6uvpthdk95T/hHa6zvxmNWbva450DIWzLiqx5NqBwBIExxdy9T9iUTWSNUMW/4yGwIHdICag5
NrapFnRaeOCo8xOMRiAau17RRr4xggItMIICKQIBATCBpjCBkTELMAkGA1UEBhMCR0IxETAPBgNV
BAoTCFZvY2FMaW5rMR8wHQYDVQQLExZTeW1hbnRlYyBUcnVzdCBOZXR3b3JrMTUwMwYDVQQLEyxD
bGFzcyAyIE1hbmFnZWQgUEtJIEluZGl2aWR1YWwgU3Vic2NyaWJlciBDQTEXMBUGA1UEAxMOSVQg
U2VjdXJpdHkgRzMCEEyXeE2lLhtL5OzAJZimqJcwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzEL
BgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTE4MDkyMDA5MDEwOVowIwYJKoZIhvcNAQkEMRYE
FC2CThLt6qgs0sX8DqpOGLmlDgxLMA0GCSqGSIb3DQEBAQUABIIBABySbgPLgKFQE9BUP/TfoRCt
eEAObnfIiD/JHu0K8iBK5yzX4nqHe6llYjpwis3M/IePV/gff2oGL1SfixtUmPiKYGukjakoYQvA
ERMRsBlHxLWZgTl0D4pdAgWfzie+eP/NLzFWnUZB+KDmzZHU1qP2KUsihoXqV3owmxeprf9EC49c
8pMGkM9uu47t6qc6pq1exqO9iDhXECIf6nF1ko1t/zRhFispfeJvtTs7lS4VwNPOKE8ktnDBx9+7
4exzfMBFHUbBozvZiQAm+IAKIHk6FuaHC5T1oypfhUzQQiJf7bHNHyv+OvBERyCugrGoBuBxTMug
HATW0ZRVBhJ7cA0=</Signature></FPSDocument>"""

        data = {'file_id': file_id, 'processing_date_short': processing_date_short, 'submission_id': submission_id, 'amount': "%.2f" % amount,
                'fpid': fpid, 'processing_time': processing_time, 'receiver_branch_code': receiver_branch_code,
                'receiver_account_number': receiver_account_number, 'reference_information': reference_information, 'orig_customer_account_name': orig_customer_account_name}

        #print xmlTemplate % data

        return xmlTemplate % data
